### ISSUE TITLE
Auto-reply

### ISSUE THREAD

**Issue by kkraman04** [ADLINK/sema-linux#7]
Testing the auto-reply function. Trial-01

**Comment by ADLINK-COM** [comment]
Thank you for opening this issue! 
  We will investigate it as soon as possible. 
  [AAE (Ask An Expert)](https://www.adlinktech.com/en/Askanexpert) will be used to investigate the issues.
  We request that you register and create an AAE ticket system, 
  including providing all the necessary information about the issue that needs to be resolved.
