### ISSUE TITLE
How do you create interrupts for GPIOs?

### ISSUE THREAD

**Issue by kyle-figure** [ADLINK/sema-linux#8]
Hello, I am using the ADLink driver, but when I export a GPIO on Linux, I do not see a `edge` file to set the rising or falling interrupt. Does this driver support interrupts for GPIOs on Linux? If so, how do we create the interrupt?

**Comment by ADLINK-COM** [comment]
Thank you for opening this issue! 
  We will investigate it as soon as possible. 
  [AAE (Ask An Expert)](https://www.adlinktech.com/en/Askanexpert) will be used to investigate the issues. 
  We request that you register and create an AAE ticket system, 
  including providing all the necessary information about the issue that needs to be resolved.
